project:
  type: book

book:
  title: "[Modeling with `tidymodels` in R](https://app.datacamp.com/learn/courses/modeling-with-tidymodels-in-r)"
  author: "[Your Name Here](your url here)"
  date: last-modified
  date-format: "[Last modified on] MMMM DD, YYYY HH:mm:ss zzz"
  chapters:
    - index.qmd
    - 01-MWTM.qmd
    #- 02-MWTM.qmd
    #- 03-MWTM.qmd
    #- 04-MWTM.qmd
    - references.qmd

execute:
  warning: false


bibliography: packages.bib

format:
  html:
    theme: pulse
    fig-width: 5
    fig-height: 4
    fig-align: "center"
    code-fold: false
  pdf:
    documentclass: scrreprt

editor: source